load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cpp",
    srcs = ["generator.go"],
    importpath = "github.com/a1ex3/l10n/internal/generator/cpp",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/generator/common",
        "//internal/parser",
        "@org_golang_x_text//cases",
        "@org_golang_x_text//language",
    ],
)
